### ISSUE TITLE
Outcome model - linear regression marginal effects bug

### ISSUE THREAD

**Issue by hannahcasey** [uoe-digicat/DigiCAT#117]
Error when running

**Comment by josiahpjking** [comment]
this looks like it is because of two things. 

1 - in extract_outcome_results(), it detects the outcome model via checking if "comparisons" %in% class(fitted_model), and then assigns 
```
extracted_outcome_results` = summary(fitted_model, conf.int = TRUE)
return(list(extracted_outcome_results, process = "cc"))
```
but the fitted_model object is already a comparison with a CI, and there's no need to pass it to summary(), so i think it needs to just be:
```
return(list(fitted_model, process = "cc"))
```
(this applies in several places i think) 

2 - the standardise_outcome_format() seems to be a big long set of ifelses, that possibly haven't been finished? in many of the conditions, there's no return() statement.
